openapi: 3.0.0
servers:
  - description: API for CU Neuron Capstone Project
    url: mockURL
info:
  description: This is the API for CU Neuron Capstone Project
  version: "1.0.0"
  title: CU Neuron Capstone Project
  contact:
    email: tikhamporntan@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: interviews
    description: |
      Questions api for exploring user needs in the first time user use the website. All questions will be stored in frontend side and will be sent the journey result (top 3) to backend side.
paths:
  /journeys:
    post:
      tags:
        - interviews
      summary: Submit user's top 3 journeys
      description: |
        Submit user's top 3 journeys. (Need to get userId from token)
        ```
          INSERT INTO user_journey (userId, journeyId)
          VALUES (6330203521, 'j1');
          INSERT INTO user_journey (userId, journeyId)
          VALUES (6330203521, 'j2');
          INSERT INTO user_journey (userId, journeyId)
          VALUES (6330203521, 'j3');
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: jid1
          in: query
          required: true
          schema: 
            type: string
        - name: jid2
          in: query
          schema: 
            type: string
        - name: jid3
          in: query
          schema: 
            type: string
      # requestBody:
      #   required: true
      #   content:
      #     application/json:
      #       schema:
      #         type: object
      #         properties:
      #           journeyId:
      #             type: array
      #             description: array of top 3 journeys' id
      #             items:
      #               type: string
      #               description: id of journey
      #             example: ["j1", "j2", "j3"]
      #         required:
      #           - data
      responses:
        201:
          description: User's journeys submitted successfully.
          content:
            application/json:
              example:
                message: User's journeys submitted successfully.
        400:
          description: Bad request. Please check the request payload.
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
