openapi: 3.0.0
servers:
  - description: API for CU Neuron Capstone Project
    url: mockURL
info:
  description: This is the API for CU Neuron Capstone Project
  version: "1.0.0"
  title: CU Neuron Capstone Project
  contact:
    email: tikhamporntan@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: landing
    description: This api is for landing page. This page contains journeys, recently visited and search bar. It has two modes (undirected graph which shows associated paths and normal mode).
paths:
  /journeys:
    get:
      tags:
        - landing
      summary: Get journeys
      description: | 
        API for getting journeys for user (Need to get userId from token)
        ```
        1. Get all journeys that user is involved
        SELECT * FROM journey WHERE id IN (SELECT journeyId FROM user_journey WHERE userId = 6330203521);

        2. Get all paths that in the journey
        SELECT * FROM path WHERE id IN (SELECT pathId FROM journey_path WHERE journeyId = 'j1'); ('j1' is example of journeyId from step 1)

        3. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 2)

        4. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 2)
        ```
      security:
        - bearerAuth: []
      responses:
        200:
          description: Get journeys successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                  journeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/Journey'
                  relationships:
                    type: array
                    items:
                      $ref: '#/components/schemas/Relationship'
                example:
                  total: 2
                  journeys:
                    - id: "j1"
                      name: "English For Business"
                      paths:
                        total: 2
                        data:
                          - id: "p1"
                            name: "Grammar"
                            description: "Sentence Structure, Syntax and Punctuation"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                            tags: 
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                            status: "Still learning"
                          - id: "p2"
                            name: "Vocabulary"
                            description: "Word and Phrases"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                            tags: 
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922512.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922513.svg"
                            status: "Passed Test"
                    - id: "j2"
                      name: "Communication Tips"
                      paths:
                        total: 1
                        data:
                          - id: "p5"
                            name: "Understanding Partner"
                            description: "How to understand your partner"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/2922513.svg"
                            tags: 
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922514.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922515.svg"
                            status: "Still learning"
                  relationships:
                    - id: "p1"
                      neighbor: ['p2']
                    - id: "p2"
                      neighbor: ['p1']
                    - id: "p5" 
                      neighbor: []
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /paths/update:
    patch:
      tags:
        - landing
      summary: Update updatedAt colmun in user_path table 
      description: | 
        - Update updatedAt colmun in user_path table (Need to get userId from token). This path is used when user click on the path.
        ```
        UPDATE user_path SET updatedAt = CURRENT_TIMESTAMP WHERE userId = 6330203521 AND pathId = 'p1';

        If the path is not in the user_path table, it will insert the path into the table.
        INSERT INTO user_path (userId, pathId, status) VALUES (6330203521, 'p1', 'Still learning');
        ```

        - There is some cases that the path may not be added to Journey page yet. (This is because the user may learn the path from search result)
        For example: 
        ```
          jourey1: path1, path2, path3
        ```
        ```
          jourey2: path1, path2, path6
        ```
        ```
          jourey3: path2, path8, path9
        ```

        - path2, path3 and all three journeys is not be added to Journey page.
        - When user learn path2 from serach result, path2 will be added to user_path table. If user also learn path3 from search result too, path3 will be added to user_path table.
        - journey1 will be added to user_journey table when path2 and path3's status is "Passed Test". So, user can see journey1 in Journey page.
        - CONCLUSION: If user learn path from search result, the path will be added to user_path table. If the path is in the journey, the journey will be added to user_journey table when more than or equal half of paths in the journey have status "Passed Test".
        ```
        1. Retrieve all journeys where more than or equal to half of the paths in the journey have the status 'Passed Test'.

        2. Insert journeyId into user_journey table
        INSERT INTO user_journey (userId, journeyId) VALUES (6330203521, 'j1'); ['j1' is example of journeyId from step 1]
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: id of path
          required: true
          schema:
            type: string
          example: "p1"
      responses:
        200:
          description: Update updatedAt colmun in user_path table successfully.
          content:
            application/json:
              example:
                message: Update updatedAt colmun in user_path table successfully.
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /paths/recently:
    get:
      tags:
          - landing
      summary: Get recently visited paths
      description: |
        API for getting recently visited paths for user (Need to get userId from token) Recently is defined as the updatedAt column in user_path table.
        ```
        1. Get all paths that user has visited
        SELECT * FROM path WHERE id IN (SELECT pathId FROM user_path WHERE userId = 6330203521 ORDER BY updatedAt DESC);

        2. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 1)

        3. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 1)
        ```
      security:
        - bearerAuth: []
      responses:
        200:
          description: Get recently visited paths successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                  paths:
                    type: array
                    items:
                      $ref: '#/components/schemas/Path'
                  relationships:
                    type: array
                    items:
                      $ref: '#/components/schemas/Relationship'
                example:
                  total: 1
                  paths:
                    - id: "p1"
                      name: "Grammar"
                      description: "Sentence Structure, Syntax and Punctuation"
                      picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                      tags: 
                        - id: "c1"
                          name: "Daily Conversation"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                        - id: "c2"
                          name: "Business"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                      status: "Still learning"
                  relationships:
                    - id: "p1"
                      neighbor: []
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /search:
    get:
      tags:
        - landing
      summary: Search specific path
      description: | 
        API for searching specific path.
        ```
        1. Get all paths that match the search query
        SELECT * FROM path WHERE name LIKE '%Grammar%';

        2. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 1)

        3. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 1 or from step 3 itself)
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: search query
          required: true
        - name: depth
          in: query
          schema:
            type: integer
          description: depth of search result
          required: true
      responses:
        200:
          description: Search successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                    description: total number of paths from the search result
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Path'
                  relationships:
                    type: array
                    items:
                      $ref: '#/components/schemas/Relationship'
                example:
                  total: 1
                  data:
                    - id: "p1"
                      name: "Grammar"
                      description: "Sentence Structure, Syntax and Punctuation"
                      picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                      tags: 
                        - id: "c1"
                          name: "Daily Conversation"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                        - id: "c2"
                          name: "Business"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                      status: "Still learning"
                  relationships:
                    - id: "p1"  # depth 0 (search result)
                      neighbor: ['p2']
                    - id: "p2"  # depth 1 
                      neighbor: ['p1', 'p3']
                    - id: "p3" # depth 2 
                      neighbor: ['p2', 'p4']
                    - id: "p4" # depth 3
                      neighbor: ['p3'] # only show path which is in the relationships
                    # p1 <--> p2 <--> p3 <--> p4
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /achievement:
    get:
      tags:
          - landing
      summary: Get achievement of each journey
      description: |
        API for getting achievement of all journeys that user is involved (Need to get userId from token)
        ```
        1. Get all journeys that user is involved
        SELECT * FROM journey WHERE id IN (SELECT journeyId FROM user_journey WHERE userId = 6330203521);

        2. Get all paths that in the journey
        SELECT * FROM path WHERE id IN (SELECT pathId FROM journey_path WHERE journeyId = 'j1'); ('j1' is example of journeyId from step 1)

        3. Get path's status in user_path table
        - passed = SELECT COUNT(*) FROM user_path WHERE userId = 6330203521 AND pathId = 'p1' AND status = 'Passed Test'; ('p1' is example of pathId from step 2)
        - total = SELECT COUNT(*) FROM user_path WHERE userId = 6330203521 AND pathId = 'p1'; ('p1' is example of pathId from step 2)
        - remainingPaths = SELECT * FROM path WHERE id IN (SELECT pathId FROM journey_path WHERE journeyId = 'j1') AND id NOT IN (SELECT pathId FROM user_path WHERE userId = 6330203521 AND status = 'Passed Test'); ('j1' is example of journeyId from step 1)
        ```
      security:
        - bearerAuth: []
      responses:
        200:
          description: Get achievement of each journey successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                    example: 1
                  journeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/JourneyAchievement'
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Journey:
      type: object
      properties:
        id:
          type: string
          example: "j1"
        name:
          type: string
          example: "English For Business"
        paths:
          type: 
            object
          properties:
            total:
              type: integer
              example: 1
            data:
              type: array
              items:
                $ref: '#/components/schemas/Path'
    JourneyAchievement:
      type: object
      properties:
        id:
          type: string
          example: "j1"
        name:
          type: string
          example: "English For Business"
        passed:
          description: amount of paths that user has passed the test
          type: integer
          example: 3
        total:
          description: total amount of paths in the journey
          type: integer
          example: 5
        remainingPaths:
          description: array of remaining paths' id (Path which has status "Still learning" or "Not visited")
          type: array
          items:
            properties:
              id:
                type: string
              name:
                type: string
          example: 
            - id: "p1"
              name: "Grammar"
            - id: "p2"
              name: "Vocabulary"
    Path:
      type: object
      properties:
        id:
          type: string
          example: "p1"
        name:
          type: string
          example: "Grammar"
        description:
          type: string
          example: "Sentence Structure, Syntax and Punctuation"
        picture:
          type: string
          description: path's picture (if the path has no picture, it will be empty string)
          example: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: status of the path (Still learning, Passed Test, Not visited)
          enum:
            - "Still learning"
            - "Passed Test"
            - "Not visited"
    Tag:
      type: object
      properties:
        id:
          type: string
          example: "c1"
        name:
          type: string
          example: "Daily Conversation"
        icon:
          type: string
          example: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
    Relationship:
      description: Relationship between paths. For the search results, it will show the relationship between the searched path and the other paths in 3 depth.
      type: object
      properties:
        id:
          type: string
          example: "p1"
        neighbor:
          type: array
          description: array of associated path's id (Show only path's id which exists in the relationships)
          items:
            type: string
          example: ['p2', 'p3', 'p4']