openapi: 3.0.0
servers:
  - description: API for CU Neuron Capstone Project
    url: mockURL
info:
  description: This is the API for CU Neuron Capstone Project
  version: "1.0.0"
  title: CU Neuron Capstone Project
  contact:
    email: tikhamporntan@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: video
    description: API for getting video for specific microlearning node
paths:
  /micros/:id:
    get:
      tags:
        - video
      summary: Get video for specific microlearning node
      description: |
        Get video for specific microlearning node
        ```
        1. Get videoId
        SELECT videoId FROM micro WHERE id = 'm1' AND type = 'video';  [m1 is an example of micro id from path parameter]

        2. Get video info
        SELECT * FROM video WHERE id = 'v1';  [v1 is an example of video id from step 1]

        2. Get documents info
        SELECT * FROM document WHERE videoId = 'v1';  [v1 is an example of video id from step 1] 
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: id of microlearning node
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get video successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  video:
                    $ref: '#/components/schemas/Video'
                  documents:
                    type: "array"
                    items:
                      $ref: '#/components/schemas/Document'
                    description: document of video (e.g file that teacher upload or use in video)
        400:
          description: Bad request. Please check the request payload.
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /micros/:id/next:
    get:
      tags:
        - video
      summary: Get next video
      description: | 
        Get next video for specific microlearning node when current video is end. 
        The next video is the video that have the "same level" as the current video. 
        If the current video is the last video in the level, the next video will be the first video in the next level.
        ```
        1. Get groupId of current micro
        SELECT groupId FROM micro WHERE id = 'm1';  [m1 is an example of micro id from path parameter]

        2. COUNT number of micro in the group
        SELECT COUNT(*) FROM micro WHERE groupId = 'g1';  [g1 is an example of group id from step 1]

        3. Get sequence of current micro (sequence column which represents the order of micro in the group)
        SELECT sequence FROM micro WHERE id = 'm1';  [m1 is an example of micro id from path parameter]

        if sequence = COUNT, it means that current micro is the last micro in the group.
          4-1. Get next group
          SELECT nextId FROM group_next WHERE id = 'g1';  [g1 is an example of group id from step 1]

          4-2 .Get videoId of micro in the next group which has sequence = 1
          SELECT videoId FROM micro WHERE groupId = 'g2' AND sequence = 1;  [g2 is an example of group id from step 4-1]

          4-3. Get video info
          SELECT * FROM video WHERE id = 'v1';  [v1 is an example of video id from step 4-2]
        else
          4-1. Get videoId of micro in the same group which has sequence = current_sequence + 1  
          SELECT videoId FROM micro WHERE groupId = 'g1' AND sequence = current_sequence + 1;  [g1 is an example of group id from step 1]

          4-2. Get video info
          SELECT * FROM video WHERE id = 'v1';  [v1 is an example of video id from step 4-1]
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: id of microlearning node
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get next video successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  nexts:
                    type: "array"
                    items:
                      $ref: '#/components/schemas/VideoNext'
                example:
                  nexts:
                    - micro:
                        id: "m1"
                        title: "How to make a cup of coffee"
                      title: "It's okay, go ahead."
                    - micro:
                        id: "m2"
                        title: "How to make a ADVANCE cup of tea"
                      title: "Give me advance example"
        400:
          description: Bad request. Please check the request payload.
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
            description: Unauthorized. Please login.
            content:
              application/json:
                example:
                  message: Unauthorized. Please login.
  /paths/:id/videos:
    get:
      tags:
        - video
      summary: Get all videos in path
      description: |
        Get all videos in path
        ```
        1. Get all groupIds in path
        SELECT id from group WHERE pathId = 'p1';  [p1 is an example of path id from path parameter]

        2. Get all micros in each group and get videoId of each micro
        SELECT videoId FROM micro WHERE groupId = 'g1' AND type = 'video';  [g1 is an example of group id from step 1]

        3. Get video info of each videoId
        SELECT * FROM video WHERE id = 'v1';  [v1 is an example of video id from step 2]
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: id of path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get all videos in path successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/VideoBeief'
        400:
          description: Bad request. Please check the request payload.
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
            description: Unauthorized. Please login.
            content:
              application/json:
                example:
                  message: Unauthorized. Please login.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    VideoBeief:
      type: object
      properties:
        microId:
          type: "string"
          example: "m1"
          description: id of microlearning node
        title:
          type: "string"
          example: "How to make a cup of coffee"
          description: title of video
        groupName:
          type: "string"
          example: "Group 1"
          description: name of group that video belong to
    VideoNext:
      type: object
      properties:
        micro:
          type: object
          properties:
            id:
              type: "string"
              example: "m1"
              description: id of microlearning node
            title:
              type: "string"
              example: "How to make a cup of coffee"
              description: title of video
        title:
          type: "string"
          example: "It's okay, go ahead."
          description: option's title of video. It will be displayed when user need to choose which video to play next.
    Video:
      type: object
      properties:
        microId:
          type: "string"
          example: "m1"
          description: id of microlearning node
        title:
          type: "string"
          example: "How to make a cup of coffee"
          description: title of video
        link:
          type: "string"
          example: "https://www.youtube.com/watch?v=1q6zleFf6pE" 
          description: resource of video 
    Document:
      type: object
      properties:
        name:
          type: "string"
          example: "manual.pdf"
          description: name of document
        link:
          type: "string"
          example: "https://mycourseville-default.s3.ap-southeast-1.amazonaws.com/useruploaded_course_files/2023_1/39312/materials/W01_WebDevFundamentals-957520-16913396401537.pdf"
          description: link of document
        